# Generated by Django 3.0 on 2019-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='language',
            field=models.BooleanField(default=False),
        ),
    ]
